// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxpnslolxrcitvokmkjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4cG5zbG9seHJjaXR2b2tta2pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NzYxNjIsImV4cCI6MjA1NTQ1MjE2Mn0.TolpAgK8FoGCn7sN-5XX_tJqcGg-v66B5bZ1WAs6RLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);